name: Sync GitHub Release

on:
  release:
    types:
      - published

jobs:
  sync-release:
    runs-on: ubuntu-latest

    steps:
      - name: Send Release to Website
        run: |
          curl -X POST "${{ secrets.WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -H "X-GitHub-Event: release" \
          -d '${{ toJson(github.event) }}'
