name: Sync GitHub Release

on:
  release:
    types:
      - published

jobs:
  sync-release:
    runs-on: ubuntu-latest

    steps:
      - name: Send Release
        run: |
          curl -X POST "${{ secrets.WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -H "x-webhook-secret: ${{ secrets.WEBHOOK_SECRET }}" \
            -d '${{ toJson(github.event) }}'
